# -*- coding: utf-8 -*-
"""data_load

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KoLwL1GrP1AxMDLjl7-xy3uqPRHhBMJa
"""

import pandas as pd

def load_data(file_path):
    """
    Load the credit card fraud dataset and apply initial cleaning.
    """
    df = pd.read_csv(file_path)

    # Standardize column names
    df.columns = df.columns.str.strip().str.lower()

    return df


def get_basic_info(df):
    """
    Print basic information about the dataset.
    """
    print("Dataset shape:", df.shape)
    print("\n Column data types:\n", df.dtypes)
    print("\n Missing values:\n", df.isnull().sum())
    print("\n Class distribution:\n", df['class'].value_counts(normalize=True))