# -*- coding: utf-8 -*-
"""shap_explainer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rxl4TWNmFvU_pKBiVenINxx0rDU9_J6E
"""

import shap
import matplotlib.pyplot as plt

def explain_model(model, X_test_scaled, sample_idx=3):
    explainer = shap.Explainer(model)
    shap_values = explainer(X_test_scaled)

    print("🔍 Global Feature Importance:")
    shap.plots.bar(shap_values, max_display=10)

    print(f"\n🔬 Local Explanation for Sample #{sample_idx}:")
    shap.plots.waterfall(shap_values[sample_idx])